# Use Nginx as a base image
FROM nginx:alpine

# Remove default Nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy frontend files to Nginx's default serving folder
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80