# Use Python 3.9 slim as base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy backend code
COPY ./backend /app/backend

# Install dependencies
RUN pip install -r /app/backend/requirements.txt

# Expose port
EXPOSE 5000

# Run Flask app
CMD ["python", "/app/backend/app.py"]
